services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.5.0
    restart: unless-stopped
    env_file: pocket-id.env
    pull_policy: if_not_present
    ports:
      - 1411:1411
    volumes:
      - "./data:/app/data"
    healthcheck:
      test: ["CMD", "/app/pocket-id", "healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
