- name: Install required dependencies
  ansible.builtin.apt:
    name: "{{ mongodb_dependencies }}"
    state: present
    update_cache: true
  no_log: true

- name: Download mongodb gpg key
  ansible.builtin.get_url:
    url: https://pgp.mongodb.com/server-{{ mongodb_version }}.asc
    dest: "{{ mongodb_key_file }}"
    mode: "0644"

- name: Add mongodb repository
  ansible.builtin.deb822_repository:
    name: mongodb
    install_python_debian: true
    architectures: [amd64]
    signed_by: "{{ mongodb_key_file }}"
    uris: ["{{ mongodb_repo_url }}"]
    # Note: This is a workaround, since mongodb doesn't have a repo in Ubuntu
    # 26.04 LTS (resolute). Once mongdb supports Ubuntu 26.04 LTS, replace
    # `noble` with `{{ ansible_facts['distribution_release'] }}`. Check if
    # mongdb supports Ubuntu 26.04 LTS with this URL:
    # https://repo.mongodb.org/apt/ubuntu/dists/resolute/mongodb-org/8.0/InRelease
    suites: ["noble/mongodb-org/{{ mongodb_version }}"]
    components: [multiverse]
    state: present

- name: Install mongodb
  ansible.builtin.apt:
    name: mongodb-org
    state: present
  no_log: true

## For debug only.
# - name: Stop the mongodb service
#   ansible.builtin.systemd:
#     name: mongod
#     state: stopped
#   no_log: true

## For debug only.
# - name: Ensure the mongodb service is started
#   ansible.builtin.systemd:
#     name: mongod
#     state: started
#     enabled: true
#   no_log: true
