# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/requirements.json

roles: []

collections:
  - name: community.docker
    version: ">=4.8.2"
