# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Apply the vcounter role
      ansible.builtin.include_role:
        name: ncat_listen
