- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Destroy test containers
      community.docker.docker_container:
        name: "{{ hostvars[item].ansible_host }}"
        force_kill: true
        state: absent
      loop: "{{ groups['all'] }}"

    - name: Destroy container network
      community.docker.docker_network:
        name: "{{ docker_network_name }}"
        state: absent
