- name: Install required dependencies
  ansible.builtin.apt:
    name: "{{ install_docker_dependencies }}"
    state: present
    update_cache: true
  no_log: true

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "{{ install_docker_gpg_url }}"
    dest: /tmp/docker.gpg
    mode: "0644"

- name: Convert Docker GPG key to binary
  ansible.builtin.command:
    cmd: gpg --dearmor -o "{{ install_docker_key_file }}" /tmp/docker.gpg
    creates: "{{ install_docker_key_file }}"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ install_docker_arch }} signed-by={{ install_docker_key_file }}]
      {{ install_docker_repo_url }}
      {{ ansible_facts['distribution_release'] }}
      stable
    state: present
    filename: docker

- name: Install Docker and Docker Compose Plugin
  ansible.builtin.apt:
    name: "{{ install_docker_packages }}"
    state: present
  no_log: true

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  no_log: true

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ install_docker_users }}"

- name: Verify Docker Compose installation
  ansible.builtin.command:
    cmd: docker compose version
  register: install_docker_compose_version
  changed_when: false

- name: Display Docker Compose version
  ansible.builtin.debug:
    msg: "{{ install_docker_compose_version.stdout }}"
