name: Run Molecule Test on a Scenario
description: Setup kubernetes, install flux, add GitRepository resource
inputs:
  scenario:
    description: The molecule scenario name
    required: true
  sops_age_key:
    description: The SOPS_AGE_KEY env var
    required: true

runs:
  using: composite
  steps:
    - name: Debug versions of required tools
      shell: sh
      run: |
        docker --version
        python --version

    - name: Install Nix
      uses: cachix/install-nix-action@v31

    - name: Decrypt encrypted.env to generate .vault_pass.txt
      env:
        SOPS_AGE_KEY: ${{ inputs.sops_age_key }}
      shell: nix shell nixpkgs#sops --quiet --command bash {0}
      run: |
        tmpfile=$(mktemp)
        sops decrypt --output-type dotenv encrypted.env >"$tmpfile"
        . "$tmpfile"
        echo "$ANSIBLE_VAULT_PASSWORD" >.vault_pass.txt

    - name: Run ansible playbook
      shell: nix develop .#ci --quiet --command bash {0}
      run: |
        molecule test --scenario-name "${{ inputs.scenario }}" --report
