name: Publish to Ansible Galaxy

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build-and-push:
    name: build and push to galaxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Build and push to Ansible Galaxy
        env:
          ANSIBLE_GALAXY_API_TOKEN: ${{ secrets.ANSIBLE_GALAXY_API_TOKEN }}
        shell: nix develop .#publish --quiet --command bash {0}
        run: sh scripts/ansible-galaxy-publish.sh
